### ISSUE TITLE
PHP deprecation notice populating $HTTP_RAW_POST_DATA

### ISSUE THREAD

**Issue by inetbiz** [martymcguire/morris#4]
```
PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
```

**Comment by martymcguire** [comment]
hi @inetbiz 

If you peek at the code for handling responses, Morris already uses `php://input` as suggested in the deprecation notice you pasted:

https://github.com/martymcguire/morris/blob/master/index.php#L7

This sounds like a server configuration issue with PHP rather than something related Morris.
